config/routes.rb
Homeschoolers::Application.routes.draw do

  get "gettogethers" => "gettogethers#index", as: 'gettogethers'

  post "gettogethers" => "gettogethers#create", as: 'create_gettogether' 

  get "gettogethers/new" => "gettogethers#new", as: 'new_gettogether'

  get "gettogethers/:id/edit" => "gettogethers#edit", as: 'edit_gettogether'

  post "gettogethers/:id/update" => "gettogethers#update", as: 'update_gettogether'

  post "gettogethers/:id/destroy" => "gettogethers#destroy", as: 'destroy_gettogether'

  get "gettogethers/:id/show" => "gettogethers#show", as: 'gettogether'

  post "add_attendee" => "gettogethers#add_attendee"

  resources :students
  resources :outcomes, :except => :new

  get "resources/add_resource/:id" => 'resources#add_resource', as: 'add_resource'

  get "outcomes/new/:student_id" => 'outcomes#new', as: 'new_outcome'

  get "resources/index"

  get "resources/new" => 'resources#new', as: 'new_resource'
  post "resources" => 'resources#create'

 delete "resources/:id" => 'resources#destroy', as: 'resources_destroy'

  get   'resources/:id/edit' => 'resources#edit', as: 'resources_edit'
  post  'resources/:id/update' => 'resources#update'

  match "resources/:id" => 'resources#show', as: 'resource'

  mount Forem::Engine, :at => '/forums'

  devise_for :educators, :controllers => {:registrations => 'registrations'}

  get   'educators/:id/edit' => 'educators#edit', as: 'educator_edit'
  post  'educators/:id/update' => 'educators#update', as: 'educator_update'

  match 'educators/:id' => 'educators#show', as: 'educator'

  get "static_pages/home"

  root to: 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


  # all resources where public => true


  def home
      @public_resources = Resource.where("public=true").order('grade_level ASC','subject ASC','name ASC')
      @students = Student.all

      if current_educator
            @my_resources = Resource.where(educator_id: current_educator.id)
            @me = Educator.where(id: current_educator.id).first
            @family = @me.family.id unless @me.family.nil?
            @my_students = Student.where(family_id: @family)

      end


  end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_fnavbar.html.erb
    <div class="header">
      <ul class="nav nav-pills pull-right">
        <li><a href="/">Home</a></li>
        <li><%= link_to "Get-togethers", main_app.gettogethers_path %> </li>
        <li><%= link_to "Forums", forem.forums_path %> </li>

        <% if params[:controller].include? "forem" %>
          <% if current_educator %>
            <li> <%= link_to "My Profile", main_app.educator_path(current_educator.id) %>
            <li><%= link_to "Sign Out",  main_app.destroy_educator_session_path, method: :delete %> </li>
          <% else %>
            <li><%= link_to "Sign In",  main_app.new_educator_session_path %> </li>
            <li><%= link_to "Sign Up",  main_app.new_educator_registration_path %> </li>
          <% end %>
        <% end %> 
      </ul>
      <h3 class="text-muted logoized"><%= link_to "kohwop", main_app.root_path %></h3>
      
    </div>
    <hr>

app/views/static_pages/_navbar.html.erb
    <div class="header">
      <ul class="nav nav-pills pull-right">
        <li><a href="/">Home</a></li>
        <li><%= link_to "Forums", forem.forums_path %> </li>
        <li><%= link_to "Get-togethers", gettogethers_path %> </li>

          <% if current_educator %>
            <li> <%= link_to "My Profile", educator_path(current_educator.id) %>
            <li><%= link_to "Sign Out",  destroy_educator_session_path, method: :delete %> </li>
          <% else %>
            <li><%= link_to "Sign In",  new_educator_session_path %> </li>
            <li><%= link_to "Sign Up",  new_educator_registration_path %> </li>
          <% end %>

      </ul>

       <h3 class="text-muted logoized"><%= link_to "kohwop", root_path %></h3>
     
    </div>

    <hr>

app/views/static_pages/_splash.html.erb
<div class="splash">
      <p class="intro_para">
         <strong><span class="logoized">  Kohwop </span></strong> makes sharing and learning easier. Kohwop opens up opportunities for you to share your experiences and read about the experiences other homeschooling parents.
       </p>

      <ul class="feature_list">
        <li>Track your students outcomes with a personalized Study planner for each child</li>
        <li>Share and search curriculum resources in the Supply Closet</li>
        <li>Manage your own curriculum and resources in your Resource Cabinet</li>
        <li>Join and create your own messaging forum in the Teachers Room</li>
      </ul>

      <%= link_to "Join the Community", new_educator_registration_path, class: "btn-info btn btn-large center" %>

      <h4>We enjoy hearing from you. How are we doing? <a href='mailto:info@kohwop.com'>Let us know! </a> </h4>

</div>

app/views/static_pages/home.html.erb
<% if current_educator.nil?  %>
        <%=  render "splash" %>

<% elsif current_educator.family.nil?%>

  <h4> To start enjoying (pretty much all of) the features of kohwop, please fill out a profile, particularly the "Family" info. </h4>

  <%= link_to "Edit My Profile", educator_edit_path(current_educator.id), class: "btn btn-info" %>




<% else %>



        <% if current_educator && current_educator.family %>
        <h1 id="family" > The <%= current_educator.family.name %> family</h1>
        <h2 id="motto"> "<%= current_educator.family.motto %>"</h2>


        <div id="students">
            <h3>My Students</h3>
          <table class="table table-striped">
            <thead>
              <th>Name</th>
              <th>Grade</th>

              <th></th>
              <th></th>
              <th></th>
            </thead>


            <% @my_students.each do |student| %>
            <tr>
                <td>  <%= student.name %> </td>
                <td>  <%= student.grade %> </td>
                <% if student.gender == 'male' %>
                    <td><img src='assets/boy.png'></td>
                  <% else %>
                    <td><img src='assets/girl.png'></td>
                  <% end %>

                <td><%= link_to 'Study Plan', student, class: 'btn btn-primary' %></td>
                <td><%= link_to 'Edit Student Profile', edit_student_path(student.id), class: 'btn btn-info' %></td>
                <td><%= link_to 'Delete Student', student, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>

          </table>

          <%= link_to 'Add a Student', new_student_path, class: "btn btn-success" %>

          <p> </p>
        </div>
        <div id="my_resources">
            <h3>My Resources</h3>
          <table class="table table-striped">
          
            <thead>
              <th>Grade</th>
              <th>Subject</th>
              <th>Description</th>
              <th></th>
              <th></th>
              <th></th>
            </thead>


            <% @public_resources.each do |resource| %>
            <tr>
                <td>  <%= resource.grade_level %> </td>
                <td>  <%= resource.subject %> </td>
                <td>  <%= resource.name %> </td>

                <td><%= link_to 'Show', resource, class: 'btn btn-info' %></td>
                <td><%= link_to 'Edit', resources_edit_path(resource.id), class: 'btn btn-warning' %></td>
                <td><%= link_to 'Destroy', resource, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>


          </table>

          <br />

          <%= link_to 'Add a Resource', new_resource_path, class: "btn btn-info" %>
          <p> </p>

        </div> <!-- my resources -->

        <div id="public_resources"><%= link_to 'Supply Cabinet', resources_index_path, class: "btn btn-info" %></div>


     <% end %>
  <% end %>