config/routes.rb
Homeschoolers::Application.routes.draw do

  get "gettogethers" => "gettogethers#index", as: 'gettogethers'

  post "gettogethers" => "gettogethers#create", as: 'create_gettogether' 

  get "gettogethers/new" => "gettogethers#new", as: 'new_gettogether'

  get "gettogethers/:id/edit" => "gettogethers#edit", as: 'edit_gettogether'

  post "gettogethers/:id/update" => "gettogethers#update", as: 'update_gettogether'

  post "gettogethers/:id/destroy" => "gettogethers#destroy", as: 'destroy_gettogether'

  get "gettogethers/:id/show" => "gettogethers#show", as: 'gettogether'

  post "add_attendee" => "gettogethers#add_attendee"

  resources :students
  resources :outcomes, :except => :new

  get "resources/add_resource/:id" => 'resources#add_resource', as: 'add_resource'

  get "outcomes/new/:student_id" => 'outcomes#new', as: 'new_outcome'

  get "resources/index"

  get "resources/new" => 'resources#new', as: 'new_resource'
  post "resources" => 'resources#create'

 delete "resources/:id" => 'resources#destroy', as: 'resources_destroy'

  get   'resources/:id/edit' => 'resources#edit', as: 'resources_edit'
  post  'resources/:id/update' => 'resources#update'

  match "resources/:id" => 'resources#show', as: 'resource'

  mount Forem::Engine, :at => '/forums'

  devise_for :educators, :controllers => {:registrations => 'registrations'}

  get   'educators/:id/edit' => 'educators#edit', as: 'educator_edit'
  post  'educators/:id/update' => 'educators#update', as: 'educator_update'

  match 'educators/:id' => 'educators#show', as: 'educator'

  get "static_pages/home"

  root to: 'static_pages#home'

end

app/models/gettogether.rb
class Gettogether < ActiveRecord::Base
  attr_accessible :description, :end_time, :lat, :long, :name, :picture, :start_time, :address, :city, :state

  has_and_belongs_to_many :educators

  geocoded_by :prep_address

  after_validation :geocode

  #before_save :convert_datetimes

  def convert_datetimes(startz, endz)

    new_time = DateTime.strptime(startz, '%m/%d/%Y %I:%M %P')

    self.start_time = new_time

    new_time2 = DateTime.strptime(endz, '%m/%d/%Y %I:%M %P')

    self.end_time = new_time2

  end    

  def prep_address

    [address, city, state].compact.join(',')

  end

end

app/controllers/gettogethers_controller.rb
class GettogethersController < ApplicationController
  def index

    @gtgs = Gettogether.all

    if params[:start_date].nil?
      datevar = Time.now.utc
    else 
      datevar = params[:start_date]
    end

    @date = Time.parse("#{datevar}")
    @start_date = Date.new(@date.year, @date.month, @date.day) 
    @events = Gettogether.find(:all, :conditions => ['start_time between ? and ?', @start_date, @start_date + 7])

  end

  def create
    @gtg = Gettogether.new(params[:gettogether])

    @gtg.convert_datetimes(params[:gettogether][:start_time], params[:gettogether][:end_time])

  

    if @gtg.save

      redirect_to gettogether_path(@gtg)

    else

      redirect_to new_gettogethers_path
    end
  end

  def new

    @gtg = Gettogether.new

  end

  def edit

    @gtg = Gettogether.find(params[:id])

  end

  def update

    @gtg = Gettogether.find(params[:id])

    @gtg.update_attributes(params[:gettogether])

  end

  def destroy
    @gtg = Gettogether.find(params[:id])
    @gtg.destroy

    redirect_to index_gettogethers_path
  end

  def show
    @gtg = Gettogether.find(params[:id])

    @educators = @gtg.educators


  end

  def add_attendee
    @educ = Educator.find(params[:eid])

    @gtg = Gettogether.find(params[:gid])


    if @gtg.educators << @educ

      redirect_to gettogether_path(@gtg.id)

    else

      redirect_to gettogethers_path

    end

  end
end

app/helpers/gettogether_helper.rb
module GettogetherHelper
end

app/views/gettogethers/_form.html.erb
<div class="gtg-form" >
<%= form_for @gtg, class: "form-vertical" do |f|  %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :start_time, class: "input-append date" %>
    <%= f.text_field :start_time, {class: 'form-control', id: "datetimepicker1", "data-format" => "MM/dd/yyyy HH:mm:ss PP", type: "text"} %>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
  </div>

    <div class="form-group">
    <%= f.label :end_time %>
    <%= f.text_field :end_time, id: "datetimepicker2", class: 'form-control' %>
        <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: 'form-control' %>
  </div>


  <div class="form-group">
    <%= f.button :submit %>
  </div>

<% end  %>


</div>

app/views/gettogethers/edit.html.erb
<h1>Gettogether#edit</h1>
<p>Find me in app/views/gettogether/edit.html.erb</p>

<%= render 'form' %>

app/views/gettogethers/index.html.erb
<div class="gtg-banner">
<h1> Get-togethers!</h1>
<p>Here are some Get-togethers you may be interested in.</p>
</div>
<div class="calendar_box" id="weekly_cal">

<div class="span6 center weeklinks"> <h3> <%= weekly_links(:date => @date) %> </h3>  </div>



</h3>
</div>
<%= weekly_calendar(@events, :date => @date, :include_24_hours => true) do |w| %>
  <%= w.week(:business_hours => params[:business_hours], :clickable_hours => true) do |event,truncate| %>

    <%=  event.start_time.strftime('%I:%M%p') %>
    <%=  link_to event.name, gettogether_path(event.id) %>
    <% end %>
  <% end %>

</div>
<div class="well"> 

  <h3> Or you can make a new one: </h3>
<p> <%= link_to "New Get-Together", new_gettogether_path, class: "btn btn-info" %> 


</div>

app/views/gettogethers/new.html.erb
<h1>Make a New Get-together!</h1>



<%= render 'form' %>

app/views/gettogethers/show.html.erb
<h2><%= @gtg.name %></h2>


<div class='clearfix'> 
  <h3> Come join us! </h3> 

   <% if @gtg.picture != '' && @gtg.picture %>
      <div class="col-12">
        <%= image_tag @gtg.picture  %>
      </div>

    <% end %>
  <p class='gtg-desc'> <%= @gtg.description %></p> 
  <div class="col-4 col-offset-2"> 
  <table class="table table-striped table-bordered">
    <tr> 
      <td> Start time:  </td><td> <%= @gtg.start_time.strftime("%A, %B %-d, %Y %-l:%M %P") %> </td>
    </tr>
    <tr> 
      <td> End time:  </td><td> <%= @gtg.start_time.strftime("%A, %B %-d, %Y %-l:%M %P") %> </td>
    </tr>
    <tr> 
      <td> Location:  </td><td> <%= raw "#{@gtg.address} <br> #{@gtg.city}, #{@gtg.state}" %> </td>
    </tr>
  </table>

   <div class="gtg-map">
    <img class="img-rounded" src="http://maps.googleapis.com/maps/api/staticmap?center=<%= @gtg.latitude %>,<%= @gtg.longitude %>&zoom=14&size=300x300&sensor=false&markers=color:blue%7Clabel:I%7C<%= @gtg.latitude %>,<%= @gtg.longitude %>&key=AIzaSyCSCtCnx4v9t1dbUR8L6In6dXZFSkuvne8"></img>


   </div>
  <% if @educators.size > 0 %>
  <h4> These homeschoolers are coming, too! </h4> 

  <ul>  
    <% @educators.each do |ed|  %>
      <li> <%= link_to  ed.username , educator_path( ed.id) %></li> 

    <% end %>

  </ul>   

  <% else  %>
    <h4> Be a "Get-together Trailblazer" </h4>
    <p> and bring a friend along, too! </p> 


  <% end %>
  <%= form_tag "#{root_url}/add_attendee", method: 'post' do %>
    <%= hidden_field_tag "eid", current_educator.id %>
    <%= hidden_field_tag "gid", @gtg.id %>

    <%= button_tag "Let's do it!", class: "btn btn-success" %>

  <% end %>
  </div>
</div>