config/routes.rb
Homeschoolers::Application.routes.draw do

  get "gettogethers" => "gettogethers#index", as: 'gettogethers'

  post "gettogethers" => "gettogethers#create", as: 'create_gettogether' 

  get "gettogethers/new" => "gettogethers#new", as: 'new_gettogether'

  get "gettogethers/:id/edit" => "gettogethers#edit", as: 'edit_gettogether'

  post "gettogethers/:id/update" => "gettogethers#update", as: 'update_gettogether'

  post "gettogethers/:id/destroy" => "gettogethers#destroy", as: 'destroy_gettogether'

  get "gettogethers/:id/show" => "gettogethers#show", as: 'gettogether'

  post "add_attendee" => "gettogethers#add_attendee"

  resources :students
  resources :outcomes, :except => :new

  get "resources/add_resource/:id" => 'resources#add_resource', as: 'add_resource'

  get "outcomes/new/:student_id" => 'outcomes#new', as: 'new_outcome'

  get "resources/index"

  get "resources/new" => 'resources#new', as: 'new_resource'
  post "resources" => 'resources#create'

 delete "resources/:id" => 'resources#destroy', as: 'resources_destroy'

  get   'resources/:id/edit' => 'resources#edit', as: 'resources_edit'
  post  'resources/:id/update' => 'resources#update'

  match "resources/:id" => 'resources#show', as: 'resource'

  mount Forem::Engine, :at => '/forums'

  devise_for :educators, :controllers => {:registrations => 'registrations'}

  get   'educators/:id/edit' => 'educators#edit', as: 'educator_edit'
  post  'educators/:id/update' => 'educators#update', as: 'educator_update'

  match 'educators/:id' => 'educators#show', as: 'educator'

  get "static_pages/home"

  root to: 'static_pages#home'

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this @resource from being saved:</h2>

        <ul>
        <% @resource.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :grade_level%>
    <%= f.text_field :grade_level, class: 'form-control' %>
  </div>


  <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>


  <div class="field form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="field form-group">
      <%= f.label :public %> <br />
      <%= f.check_box :public %> <br />
  </div>

   <%= hidden_field_tag "outcome_id", @outcome.id unless @outcome.nil? %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/add_resource.html.erb
<h1>Add a new Resource</h1>

<%= render 'form' %>



<%= link_to 'Back', root_path %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>The Supply Cabinet</h1>

<table class="table table-striped">
  <thead>
    <th>Grade</th>
    <th>Subject</th>
    <th>Description</th>
    <th>Submitted by:</th>
    <th></th>
    <th></th>
  </thead>


  <% @public_resources.each do |resource| %>
  <tr>
      <td>  <%= resource.grade_level %> </td>
      <td>  <%= resource.subject %> </td>
      <td>  <%= resource.name %> </td>
      <td>  <%= resource.educator.username %> </td>

      <td><%= link_to 'Show', resource %></td>
  </tr>
<% end %>


</table>

<br />

app/views/resources/new.html.erb
<h1>Add a new Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>


<h3> Resource: ' <%=  @resource.name %> '</h3>

<p> Description:  <%= @resource.description %> </p>

<p> Link: <%= link_to @resource.url , @resource.url %></p>

<p> <%= "Grade : #{@resource.grade_level} - "%> </p> 
<p>  <%= "Subject: #{@resource.subject} "  %> </p>

<p> <%= "Price : #{ number_to_currency @resource.price.to_s}  "  %> </p>

<p> Public:  <%= @resource.public? ? "Yes" : "No"   %> </p>


<%= link_to 'Edit', resources_edit_path(@resource) %> |
<%= link_to 'Back', resources_path %>