config/routes.rb
Homeschoolers::Application.routes.draw do

  get "gettogethers" => "gettogethers#index", as: 'gettogethers'

  post "gettogethers" => "gettogethers#create", as: 'create_gettogether' 

  get "gettogethers/new" => "gettogethers#new", as: 'new_gettogether'

  get "gettogethers/:id/edit" => "gettogethers#edit", as: 'edit_gettogether'

  post "gettogethers/:id/update" => "gettogethers#update", as: 'update_gettogether'

  post "gettogethers/:id/destroy" => "gettogethers#destroy", as: 'destroy_gettogether'

  get "gettogethers/:id/show" => "gettogethers#show", as: 'gettogether'

  post "add_attendee" => "gettogethers#add_attendee"

  resources :students
  resources :outcomes, :except => :new

  get "resources/add_resource/:id" => 'resources#add_resource', as: 'add_resource'

  get "outcomes/new/:student_id" => 'outcomes#new', as: 'new_outcome'

  get "resources/index"

  get "resources/new" => 'resources#new', as: 'new_resource'
  post "resources" => 'resources#create'

 delete "resources/:id" => 'resources#destroy', as: 'resources_destroy'

  get   'resources/:id/edit' => 'resources#edit', as: 'resources_edit'
  post  'resources/:id/update' => 'resources#update'

  match "resources/:id" => 'resources#show', as: 'resource'

  mount Forem::Engine, :at => '/forums'

  devise_for :educators, :controllers => {:registrations => 'registrations'}

  get   'educators/:id/edit' => 'educators#edit', as: 'educator_edit'
  post  'educators/:id/update' => 'educators#update', as: 'educator_update'

  match 'educators/:id' => 'educators#show', as: 'educator'

  get "static_pages/home"

  root to: 'static_pages#home'

end

app/models/outcome.rb
class Outcome < ActiveRecord::Base
  attr_accessible :description, :grade_level, :subject, :resource_id, :due_date, :student_id, :finish_date

  belongs_to :student
  belongs_to :resource
end

app/controllers/outcomes_controller.rb
class OutcomesController < ApplicationController
  # GET /outcomes
  # GET /outcomes.json


  def index
    @outcomes = Outcome.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @outcomes }
    end
  end

  # GET /outcomes/1
  # GET /outcomes/1.json
  def show
    @outcome = Outcome.find(params[:id])
    @student = @outcome.student

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @outcome }
    end
  end

  # GET /outcomes/new
  # GET /outcomes/new.json
  def new
    @outcome = Outcome.new
    @student = Student.find_by_id(params[:student_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @outcome }
    end
  end

  # GET /outcomes/1/edit
  def edit
    @outcome = Outcome.find(params[:id])
    @outcome.student_id = @student.id
    @outcome.save

  end

  # POST /outcomes
  # POST /outcomes.json
  def create
    @outcome = Outcome.new(params[:outcome])
    @outcome.save

    respond_to do |format|
      if @outcome.save
        format.html { redirect_to @outcome, notice: 'Outcome was successfully created.' }
        format.json { render json: @outcome, status: :created, location: @outcome }
      else
        format.html { render action: "new" }
        format.json { render json: @outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /outcomes/1
  # PUT /outcomes/1.json
  def update
    @outcome = Outcome.find(params[:id])

    respond_to do |format|
      if @outcome.update_attributes(params[:outcome])
        format.html { redirect_to @outcome, notice: 'Outcome was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outcomes/1
  # DELETE /outcomes/1.json
  def destroy
    @outcome = Outcome.find(params[:id])
    @outcome.destroy

    respond_to do |format|
      format.html { redirect_to outcomes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/outcomes_helper.rb
module OutcomesHelper
end

app/views/outcomes/_form.html.erb
  <%= form_for(@outcome) do |f| %>
  <% if @outcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outcome.errors.count, "error") %> prohibited this outcome from being saved:</h2>

      <ul>
      <% @outcome.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :grade_level %>
    <%= f.text_field :grade_level %>
  </div>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>


  <div class="field">
    <%= f.label :due_date %>
    <%= f.text_field :due_date %>
  </div>

  <div class="field">
    <%= f.label :finish_date %>
    <%= f.text_field :finish_date %>
  </div>


  <%= hidden_field_tag "outcome[student_id]", @student.id %>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outcomes/edit.html.erb
<h1>Editing outcome</h1>

<%= render 'form' %>

<%= link_to 'Show', @outcome %> |
<%= link_to 'Back', outcomes_path %>

app/views/outcomes/index.html.erb
<h1>Listing outcomes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outcomes.each do |outcome| %>
  <tr>
    <td><%= link_to 'Show', outcome %></td>
    <td><%= link_to 'Edit', edit_outcome_path(outcome) %></td>
    <td><%= link_to 'Destroy', outcome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Outcome', new_outcome_path %>

app/views/outcomes/new.html.erb
<h4> Adding a new outcome for <%= @student.name %>'s' Study Plan</h4>

<%= render 'form' %>

<%= link_to 'Back', outcomes_path %>

app/views/outcomes/show.html.erb
<p id="notice"><%= notice %></p>

<h4> <%= @student.name %> Study Plan</h4>


<p> Description:  <%= @outcome.description %> </p>

<p> Grade level: <%= @outcome.grade_level  %> </p>

<p> Subject: <%= @outcome.subject  %> </p>

<p> Due date: <%= @outcome.due_date  %> </p>



<%= link_to 'Edit', edit_outcome_path(@outcome) %> |
<%= link_to 'Back', student_path(@student.id) %>